on: [push, pull_request]

name: revdepcheck-top

jobs:
  R-CMD-check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"    

    timeout-minutes: 30

    runs-on: ubuntu-latest

    name: ${{ matrix.config.pkg }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { r: "release", pkg: "cSEM"            }
          - { r: "release", pkg: "dipsaus"         }
          - { r: "release", pkg: "EFAtools"        }
#          - { r: "release", pkg: "EGAnet"          }  ## libglpk.so missing
#          - { r: "release", pkg: "elevatr"         }  ## libproj.so missing
          - { r: "release", pkg: "fabletools"      }
          - { r: "release", pkg: "fxTWAPLS"        }
#          - { r: "release", pkg: "lava"            }  ## req's Bioc pkgs
#          - { r: "release", pkg: "nflfastR"        }
#          - { r: "release", pkg: "poppr"           }  ## fails to install
#          - { r: "release", pkg: "Seurat"          }
          - { r: "release", pkg: "SimDesign"       }
#          - { r: "release", pkg: "tidySEM"         }  ## fails to install
          - { r: "release", pkg: "tsdistributions" }
          - { r: "release", pkg: "tsgarch"         }
          
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      ## R CMD check
      _R_CHECK_LENGTH_1_CONDITION_: true
      _R_CHECK_LENGTH_1_LOGIC2_: true
      _R_CHECK_MATRIX_DATA_: true
      _R_CHECK_CRAN_INCOMING_: false
      
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y tidy

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::remotes
            any::sessioninfo
            any::covr
          needs: check

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          install.packages(".", repos=NULL, type="source")
          install.packages("${{ matrix.config.pkg }}", dependencies=TRUE)
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Check reverse dependency package
        run: |
          url=$(Rscript -e "cat(remotes:::download_version_url('${{ matrix.config.pkg }}', version=NULL, repos='https://cloud.r-project.org', type='source'))")
          wget "$url"
          R_PROGRESSR_ENABLE=true
          R CMD check --no-manual --as-cran "$(basename "$url")"

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-revdep${{ matrix.config.pkg }}-results
          path: ${{ matrix.config.pkg }}.Rcheck
